name: Artifacts

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  container-images:
    name: Container images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Calculate container image tags
        id: tags
        env:
          DOCKER_IMAGES: "ghcr.io/sagikazarmark/argocd-operator-util"
        run: |
          VERSION=$(head -1 Dockerfile | cut -d ':' -f 2)
          TAGS=()
          for image in $DOCKER_IMAGES; do
            TAGS+=("${image}:${VERSION}")
            TAGS+=("${image}:${VERSION}-build.${{ github.run_number }}")
          done
          echo ::set-output name=tags::$(IFS=,; echo "${TAGS[*]}")

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
        if: github.event_name == 'push'

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.tags.outputs.tags }}
          context: .
